Docker fix
RailsGirlsCPH/mentor-mentee-platform pull request #320
Opened 2020-10-10 20:38 UTC by cecastosic

@sibsmc I had errors while trying to run docker compose -up command:

`Installing pg 1.2.3 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /usr/local/bundle/gems/pg-1.2.3/ext
/usr/local/bin/ruby -I /usr/local/lib/ruby/2.6.0 -r
./siteconf20201010-6-1j9m960.rb extconf.rb
checking for pg_config... yes
Using config values from /usr/bin/pg_config
checking for libpq-fe.h... yes
checking for libpq/libpq-fs.h... yes
checking for pg_config_manual.h... yes
checking for PQconnectdb() in -lpq... no
checking for PQconnectdb() in -llibpq... no
checking for PQconnectdb() in -lms/libpq... no
Can't find the PostgreSQL client library (libpq)
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers. `

After adding libxslt1-dev libffi-dev postgresql-client-common postgresql-client, the command worked fine.

Can you please test?

2020-10-11 09:53 UTC, sibsmc requested changes
How about we just add postgresql-client initially, as the errors you showed referenced pg. I think the other libraries are included in other gems.

2020-10-11 09:53 UTC, sibsmc commented on server/Dockerfile
> +    && apt-get install -y --no-install-recommends nodejs libpq-dev libxslt1-dev libffi-dev postgresql-client-common postgresql-client
I think that we need postgresql-client 

The others are listed as included in other packages. postgresql-client-common is part of postgresql-clent and libxslt1-dev is part of nokogiri. 

Shall we start by adding postgresql-client?

2020-10-15 08:55 UTC, olleolleolle approved these changes
This change makes the Dockerfile more perfect and complete.

Thanks!

2020-10-15 09:43 UTC, sibsmc approved these changes

2020-10-15 09:43 UTC, merged