Sign up form by design
RailsGirlsCPH/mentor-mentee-platform pull request #326
Opened 2020-11-01 15:00 UTC by cecastosic

![Screen-Recording-2020-11-01-at-1](https://user-images.githubusercontent.com/10253713/97806293-416a0180-1c5b-11eb-90d2-6ba5366a581b.gif)

2020-11-08 22:26 UTC, sibsmc requested changes
In order for storybook to find Input.css I needed to move it into the src/components/input/ directory. Once I changed that though I was able to view it in the browser.

2020-11-11 19:08 UTC, cecastosic commented
@sibsmc Mac has an issue with case-sensitivity and renaming of files. On my laptop, I can see 
<img width="342" alt="Screenshot 2020-11-11 at 19 47 23" src="https://user-images.githubusercontent.com/10253713/98853532-8eb75180-2459-11eb-9658-6cbb454e917b.png">

but on your laptop, those are in two different folders.
I think I fix it now, but please check. 🙂

2020-11-13 18:55 UTC, sibsmc commented
perfect!

2020-11-13 18:55 UTC, sibsmc approved these changes

2020-11-13 18:58 UTC, merged