1115 add data columns
RailsGirlsCPH/mentor-mentee-platform pull request #328
Opened 2020-11-15 20:48 UTC by sibsmc

add fields to api_user, #276

2020-11-29 13:50 UTC, cecastosic requested changes
PR needs to be updated 🙂

2021-03-29 10:49 UTC, sibsmc commented
Changed this PR so that it only includes changes associated with additional data column. Other changes will be in separate PR

2021-03-29 11:14 UTC, olleolleolle approved these changes
This adds a new pair of columns, and the linting passes!

2021-03-29 11:42 UTC, cecastosic approved these changes

2021-03-29 11:42 UTC, merged